import React from "react";

function Dashboard() {
  const metrics = [
    { name: 'Views', value: '721K' },
    { name: 'Visits', value: '367K' },
    { name: 'New Users', value: '1,156' },
    { name: 'Active Users', value: '239K' }
  ];

  return (
    <div>
      <div className="period-selector">
        <div className="period-text">Today</div>
        <span className="period-icon">▼</span>
      </div>

      {/* Metrics Cards */}
      <div className="metrics-grid">
        {metrics.map((metric) => (
          <div key={metric.name} className="metric-card">
            <div className="metric-name">{metric.name}</div>
            <div className="metric-value">{metric.value}</div>
          </div>
        ))}
      </div>
      <p>
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
        vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
      </p>
    </div>
  );
}

export default Dashboard;